# Generated by Django 2.2.3 on 2019-07-03 12:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_from', models.CharField(max_length=30, verbose_name='From')),
                ('to', models.CharField(max_length=30, verbose_name='To')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date of Trip')),
                ('Time', models.TimeField(blank=True, null=True, verbose_name='Time of Trip')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Booked'), (3, 'Completed'), (4, 'Canceled')], default=1, verbose_name='Status')),
                ('available_seats', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Available Seats')),
                ('comments', models.CharField(max_length=30, null=True, verbose_name='Comment')),
                ('vehicle', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
    ]
